// Single source of truth for every top-level section of the site, across all
// three docs plugin instances (default/ELN, "repo", "labimotion") -- label +
// href only, nothing content-bearing.
//
// This can't be derived automatically: `sidebarItemsGenerator` runs scoped to
// one plugin instance at a time (see sidebarItemsGeneratorRepo.js /
// sidebarItemsGeneratorLabimotion.js), with no access to another instance's
// loaded docs/sidebar at that point in Docusaurus's plugin lifecycle. So this
// list is manually kept in sync with the actual site structure -- if a
// section in docs/<section>/index.mdx or docs/services/_category_.yml is
// renamed, reordered, or removed, update it here too.
//
// Three consumers share this list:
// - sidebarItemsGenerator.js (main/default instance) splices the
//   "Chemotion Repository" and "Chemotion LabIMotion" entries into the
//   autogenerated sidebar, since those live in separate plugin instances and
//   have no real folder under docs/ for the generator to find.
// - sidebars-repo.js mirrors every *other* entry (i.e. all but "Chemotion
//   Repository" itself) as plain links around its own expanded section.
// - sidebars-labimotion.js does the same, excluding "Chemotion LabIMotion"
//   itself.
module.exports = [
  { label: "Welcome", href: "/docs/" },
  { label: "Chemotion ELN", href: "/docs/eln" },
  { label: "Chemotion Repository", href: "/docs/repo" },
  { label: "Chemotion LabIMotion", href: "/docs/labimotion" },
  { label: "Services", href: "/docs/category/services" },
  { label: "Development", href: "/docs/development" },
  { label: "This Documentation", href: "/docs/documentation" },
];
