// Mirrors every *other* top-level site section as plain links (Repository is
// a separate, unversioned docs plugin instance -- see docusaurus.config.js --
// so it can't reference other instances' docs by id; these are plain hrefs,
// listed in mainSiteSections.js). Repository's own section is the one that's
// actually expanded here, via sidebarItemsGeneratorRepo.js wrapping the
// autogenerated block below into a single "Chemotion Repository" category,
// inserted at the position "Chemotion Repository" occupies in
// mainSiteSections.js. This keeps the sidebar visually continuous when
// navigating between instances, even though each instance still technically
// renders its own sidebar config.
const mainSiteSections = require("./mainSiteSections.js");

const selfIndex = mainSiteSections.findIndex(
  (s) => s.label === "Chemotion Repository",
);
const before = mainSiteSections.slice(0, selfIndex);
const after = mainSiteSections.slice(selfIndex + 1);

module.exports = {
  sidebar: [
    ...before.map((s) => ({ type: "link", ...s })),
    {
      type: "autogenerated",
      dirName: ".",
    },
    ...after.map((s) => ({ type: "link", ...s })),
  ],
};
