// The "repo" docs plugin instance's own root autogenerated block puts its
// index page (repo-docs/index.mdx, id "repo") as a flat sibling item next to
// its own subsections (Details and Standards, Workflow, etc.) rather than
// wrapping them -- because from *this* instance's perspective, repo-docs IS
// the root, and the "index doc becomes the category link, excluded from its
// own item list" treatment only applies to subfolders discovered while
// walking a directory, never to the directory passed in as `dirName` itself
// (see sidebarItemsGenerator.js for the fuller explanation / source
// reference).
//
// This wraps that flat list into a single "Chemotion Repository" category,
// using the repo index doc as the category's own link and folding every
// other top-level item underneath it -- so repo's own sidebar reads the same
// way "Chemotion ELN" etc. do in the main sidebar.
const logger = require("@docusaurus/logger").default;

async function sidebarItemsGeneratorRepo({
  defaultSidebarItemsGenerator,
  ...args
}) {
  const items = await defaultSidebarItemsGenerator(args);
  const indexIdx = items.findIndex(
    (item) => item.type === "doc" && item.id === "repo",
  );
  if (indexIdx === -1) {
    // Fallback: index doc not found (e.g. repo-docs/index.mdx lost its
    // `id: repo` frontmatter) -- return unwrapped rather than silently
    // produce an empty sidebar, but warn since this means the "Chemotion
    // Repository" wrapping category won't be built at all.
    logger.warn(
      'sidebarItemsGeneratorRepo: couldn\'t find the repo index doc (expected id "repo") to wrap the Repository sidebar around. Returning the flat, unwrapped item list instead.',
    );
    return items;
  }
  const indexItem = items[indexIdx];
  const rest = items.filter((_, i) => i !== indexIdx);
  return [
    {
      type: "category",
      label: indexItem.label ?? "Chemotion Repository",
      link: { type: "doc", id: indexItem.id },
      items: rest,
    },
  ];
}

module.exports = sidebarItemsGeneratorRepo;
