// Splices the "Chemotion Repository" link into the autogenerated sidebar,
// right after the "Chemotion ELN" category -- restoring its original
// sidebar_position: 2 placement from before Repository moved to its own
// docs plugin instance (see docusaurus.config.js).
//
// This has to be done as a post-processing step on the *default* generator's
// output (rather than declared directly in sidebars.js) because manually
// wrapping each top-level folder in its own category + nested
// `{ type: "autogenerated", dirName: "<folder>" }` does NOT get the same
// "use the folder's index doc as the category link and exclude it from the
// item list" treatment that `dirName: "."` gives every folder it discovers.
// That special-casing only fires for subfolders *discovered* during
// generation, not for whatever directory is passed in as `dirName` itself --
// confirmed by reading node_modules/@docusaurus/plugin-content-docs/src/
// sidebars/generator.js. Manually rebuilding the categories caused each
// one's own index doc to appear twice (once as the category's link, once
// again as a duplicate child item). Splicing into the default generator's
// already-correct output avoids that entirely.
const logger = require("@docusaurus/logger").default;

async function sidebarItemsGenerator({
  defaultSidebarItemsGenerator,
  ...args
}) {
  const items = await defaultSidebarItemsGenerator(args);
  const elnIndex = items.findIndex(
    (item) => item.type === "category" && item.link?.id === "eln/eln",
  );
  const repoLink = {
    type: "link",
    label: "Chemotion Repository",
    href: "/docs/repo",
  };
  if (elnIndex === -1) {
    // Fallback: ELN category not found (e.g. docs/eln/index.mdx lost its
    // `id: eln` frontmatter, or the folder was restructured) -- append at the
    // end rather than silently drop the link, but warn loudly since this
    // means "Chemotion Repository" landed somewhere other than its intended
    // position and nothing else would surface that.
    logger.warn(
      "sidebarItemsGenerator: couldn't find the Chemotion ELN category (expected link.id \"eln/eln\") to splice \"Chemotion Repository\" after. Appending it at the end of the sidebar instead.",
    );
    return [...items, repoLink];
  }
  return [
    ...items.slice(0, elnIndex + 1),
    repoLink,
    ...items.slice(elnIndex + 1),
  ];
}

module.exports = sidebarItemsGenerator;
