// Mirrors the main sidebar's top-level items as plain links (Repository is a
// separate, unversioned docs plugin instance -- see docusaurus.config.js --
// so it can't reference the main instance's docs by id; these are plain
// hrefs, listed in mainSiteSections.js). Repository's own section is the one
// that's actually expanded here, via sidebarItemsGeneratorRepo.js wrapping
// the autogenerated block below into a single "Chemotion Repository"
// category. This keeps the sidebar visually continuous when navigating
// between instances, even though each instance still technically renders its
// own sidebar config.
const mainSiteSections = require("./mainSiteSections.js");

const [beforeRepo, afterRepo] = (() => {
  const elnIdx = mainSiteSections.findIndex(
    (s) => s.label === "Chemotion ELN",
  );
  return [
    mainSiteSections.slice(0, elnIdx + 1),
    mainSiteSections.slice(elnIdx + 1),
  ];
})();

module.exports = {
  sidebar: [
    ...beforeRepo.map((s) => ({ type: "link", ...s })),
    {
      type: "autogenerated",
      dirName: ".",
    },
    ...afterRepo.map((s) => ({ type: "link", ...s })),
  ],
};
