// The "labimotion" docs plugin instance's own root autogenerated block puts
// its index page (labimotion-docs/index.mdx, id "labimotion") as a flat
// sibling item next to its own subsections (Designer, User, etc.) rather
// than wrapping them -- because from *this* instance's perspective,
// labimotion-docs IS the root, and the "index doc becomes the category link,
// excluded from its own item list" treatment only applies to subfolders
// discovered while walking a directory, never to the directory passed in as
// `dirName` itself (see sidebarItemsGenerator.js for the fuller explanation /
// source reference).
//
// This wraps that flat list into a single "Chemotion LabIMotion" category,
// using the labimotion index doc as the category's own link and folding
// every other top-level item underneath it -- so labimotion's own sidebar
// reads the same way "Chemotion ELN" etc. do in the main sidebar.
//
// This runs once per version of the labimotion instance (it's versioned,
// unlike "repo") -- the doc `id` matched below is the frontmatter id
// ("labimotion"), which stays stable across versions, exactly as
// sidebarItemsGenerator.js's "eln/eln" match already does for the versioned
// default instance.
const logger = require("@docusaurus/logger").default;

async function sidebarItemsGeneratorLabimotion({
  defaultSidebarItemsGenerator,
  ...args
}) {
  const items = await defaultSidebarItemsGenerator(args);
  const indexIdx = items.findIndex(
    (item) => item.type === "doc" && item.id === "labimotion",
  );
  if (indexIdx === -1) {
    // Fallback: index doc not found (e.g. labimotion-docs/index.mdx lost its
    // `id: labimotion` frontmatter) -- return unwrapped rather than silently
    // produce an empty sidebar, but warn since this means the "Chemotion
    // LabIMotion" wrapping category won't be built at all.
    logger.warn(
      'sidebarItemsGeneratorLabimotion: couldn\'t find the labimotion index doc (expected id "labimotion") to wrap the LabIMotion sidebar around. Returning the flat, unwrapped item list instead.',
    );
    return items;
  }
  const indexItem = items[indexIdx];
  const rest = items.filter((_, i) => i !== indexIdx);
  return [
    {
      type: "category",
      label: indexItem.label ?? "Chemotion LabIMotion",
      link: { type: "doc", id: indexItem.id },
      items: rest,
    },
  ];
}

module.exports = sidebarItemsGeneratorLabimotion;
