name: deploy CI
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
#  pull_request:
    branches: [ master ]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #    container: node:12.18.3

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - env:
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_SEARCH_API_KEY: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}
          INDEX_NAME: ${{ secrets.INDEX_NAME }}
        #          DEPLOY: ${{ secrets.DEPLOY }}
        #          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        run: |
          npm ci
          npm run build --if-present
          mkdir chemotion_saurus
          mv ./build ./public
  deploy:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
#        uses: easingthemes/ssh-deploy@v2
        env:
          DEPLOY: ${{ secrets.DEPLOY }}
        run: |
          mkdir chemotion_saurus
          mv ./build ./public
          { . $DEPLOY ; } 1> /dev/null

