name: deploy CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
# pull_request:
    branches: [ master ]

jobs:
  deploy:
    if: ${{ true }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup ssh
      # if: env.DEPLOY == 'true'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        #!/usr/bin/env bash
        set -euo pipefail
        eval $(ssh-agent -s);
        mkdir ~/.ssh/
        chmod 700 ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-add ~/.ssh/id_rsa
        touch ~/.ssh/known_hosts
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        scp -r -o StrictHostKeyChecking=no  ./public/* docusaurus@eln.chemotion.net:chemotion_saurus/.
